version: "2"
services:
    src:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./src:/var/www/html/
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8000:80
        environment:
            MYSQL_ROOT_PASSWORD: admin
volumes:
    persistent:
